(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("form"),s={firstName:o.querySelector('input[name="first_name"]'),email:o.querySelector('input[name="email"]')};function i(e,t){t?(e.style.transition="border-color 0.3s ease, box-shadow 0.3s ease",e.style.border="0.4px solid rgba(255, 0, 0, 0.5)",e.style.boxShadow="0 0 6px rgba(255, 0, 0, 0.3)"):(e.style.border="1px solid #ddd",e.style.boxShadow="none")}Object.values(s).forEach(e=>{e.addEventListener("input",()=>{i(e,!1)})}),o.addEventListener("submit",e=>{e.preventDefault();let t=!0;if(Object.entries(s).forEach(([d,c])=>{c.value.trim()||(i(c,!0),t=!1)}),!t)return;const r=new FormData(o),a=`
        First Name: ${r.get("first_name")||"Not provided"}

        Last Name: ${r.get("last_name")||"Not provided"}

        Email: ${r.get("email")||"Not provided"}

        Message: ${r.get("message")||"Not provided"}
      `;n("yachtdreamjob@gmail.com",a),n("ktretyakova1927@gmail.com",a),o.submit()});function n(e,t){fetch("https://your-email-api-endpoint.com/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:e,subject:"New Contact Form Submission",text:t})}).then(r=>{r.ok||console.error(`Failed to send email to ${e}`)}).catch(r=>{console.error("Error sending email:",r)})}});
//# sourceMappingURL=index.js.map
